### ISSUE TITLE
session_start() got warning message

### ISSUE THREAD

**Issue by yuonceruyi** [nono303/PHP7-memcache-dll#1]
#PHP Version 7.1.0  MSVC14  x64  API20160303,TS,VC14 
https://github.com/nono303/PHP7-memcache-dll/tree/master/vc14/x64/ts/php-7.1.x_memcache.dll

session_start got this:
Warning: session_start(): Failed to read session data: memcache (path: 127.0.0.1:11211)

**Comment by laurinkeithdavis** [comment]
Do you have session.save_handler set to memache? I had to change my to user and use the class included in this repo as
session_set_save_handler(MemcacheSessionHandlerPrepend());

**Comment by yuonceruyi** [comment]
session.save_handler is set to memcache , session.save_path  127.0.0.1:11211.
it works well on php-v7.0.x

**Comment by laurinkeithdavis** [comment]
Yes, I realize that it works in php-v7.0x, but it does not work in 7.1 (but I don't know why).

**Comment by yuonceruyi** [comment]
ok,thanks for replay , i 'll close this issue
