### ISSUE TITLE
New build for 7.2 ?

### ISSUE THREAD

**Issue by j16sdiz** [nono303/PHP7-memcache-dll#10]
May I have a new VC15/7.2/NTS build?

I am hitting this bug: https://github.com/websupport-sk/pecl-memcache/pull/26 , would be nice if you can provide a new version for 7.2

**Comment by nono303** [comment]
Hi @j16sdiz,
Did you just tried php-7.3.x_memcache.dll on your php 7.2 ?
Does-it fail / crash ? what the message ?

**Comment by nono303** [comment]
done on commit [f8a42a0](https://github.com/nono303/PHP7-memcache-dll/commit/f8a42a08d902ef29b3b9c34d3778629f409b4f36)
