### ISSUE TITLE
Memcached ext >= 2.2.0 is required

### ISSUE THREAD

**Issue by adityarai** [nono303/PHP7-memcache-dll#11]
I'm trying to use memcache for Symfony 4 in windows 7 using php 7.2  and memcached server version 1.5.14 .  
DLL in use:  vc15/x64/ts/php-7.2.x_memcache.dll
Error during runtime:
Memcached ext >= 2.2.0 is required

**Comment by nono303** [comment]
hi @adityarai,
you are confused between [pecl memcached extension](https://pecl.php.net/package/memcached) required for your app and [pecl memcache extension](https://pecl.php.net/package/memcache) that I provide in this repo
