### ISSUE TITLE
Getting wrong value from single memcache server, used by two different PHP versions.

### ISSUE THREAD

**Issue by smilingtearz** [nono303/PHP7-memcache-dll#13]
Hello there,

I have deployed PHP 5.4.5 and PHP 7.3 on two different servers.
PHP 5.4.5 is using its old compaitable version of memcache.dll while for PHP 7.3 I have downloaded your version of memcache (vcs15->x64->ts), I have also included your provided memcache.ini in my php.ini file.
Both the PHP 5.4.5 and PHP 7.3 are connection to the same memcache server.
Now the problem is:

When I set memcache value from PHP 7.3, the value is available on 5.4.5.
But when I set value on PHP 5.4.5, and then try to get the value from PHP 7.3 it mostly return false. (i.e in 4 out of 10 requests).

Also if I set value on PHP 7.3, then replace the value. And when I get it using the same PHP version, it sometimes return the old value (i.e. in 2 out of 10 requests).

Kindly if you can help in resolving this issue.
Thanks

**Comment by nono303** [comment]
I @smilingtearz,
Strange behavior but actually i just provided win release of memcache pecl extension from sources (no change)
So I suppose you may ask to hradtke@php.net (cf. https://github.com/websupport-sk/pecl-memcache)

**Comment by qmegas** [comment]
@smilingtearz Facing same exact issue. But I have two servers with 5.6 and 7.3
Have you found a solution?

**Comment by smilingtearz** [comment]
Yes, the issue was that: we were having x86 (32bit) memcache.dll for 5.4 and x64(64bit) for 7.3.
We replaced the php 5.4 memcache.dll with x64 version and it resolved the issue.

**Comment by smilingtearz** [comment]
> @smilingtearz Facing same exact issue. But I have two servers with 5.6 and 7.3
> Have you found a solution?

Yes, the issue was that: we were having x86 (32bit) memcache.dll for 5.4 and x64(64bit) for 7.3.
We replaced the php 5.4 memcache.dll with x64 version and it resolved the issue.
