### ISSUE TITLE
Is there a bug with prefix_host_key?

### ISSUE THREAD

**Issue by juongithub** [nono303/PHP7-memcache-dll#14]
Could you confirm that the following bug does not depend on compilation? I am using the DLL version without AVX (VC15 and VC16 versions have the same problem).
https://github.com/websupport-sk/pecl-memcache/issues/56

**Comment by nono303** [comment]
Can't confirm (I'm just compiling...) but didn't see any reason to be a compilation issue

**Comment by juongithub** [comment]
thank you
