### ISSUE TITLE
Inconsistency when connecting remote memcached server

### ISSUE THREAD

**Issue by qmegas** [nono303/PHP7-memcache-dll#15]
### Environment
OS: Windows 10
PHP version: `php 7.3 x64 ts` and `php 7.2 x64 ts` (bug checked and confirmed in these versions, but probably it presents in other versions too)
Memcached server: different versions on unix-like systems (Linux, Ubuntu) - **require remote memcached server. doesn't work with local windows memcached server**

### Steps to reproduce
Step 1: Run many times this script through your browser (about 30-40 times, just quickly press F5)
```php
$memcache = new Memcache();
$memcache->addServer("ip.of.your.remote.server", 11211);
$memcache->set('test', 10, 0, 6000);
```

Step 2: Now change stored value (for example 20) and run script only **one time**:
```php
$memcache = new Memcache();
$memcache->addServer("ip.of.your.remote.server", 11211);
$memcache->set('test', 20, 0, 6000);
```

Step 3: Now change this script like that:
```php
$memcache = new Memcache();
$memcache->addServer("ip.of.your.remote.server", 11211);
echo $memcache->get('test');
```

You will see that it return you `20`, but sometimes it returns `10`!!!
Bug checked on different computers with Windows 10 and different remote servers.
Doesn't reproducible with local windows memcached server.

I guess there is some kind hashing inconsistency, so on step 1, when you store many times same value, it stores under different keys. On step 2, when you run it only once it changes the value, but only for one specific key, so when on step 3 you start to retrieve stored value, due to inconsistency you receive different values!

Another interesting finding, is that this bug presents only in latest builds. I have downloaded DLL from Dec 13, 2018 (for php 7.3 x64 ts) and it works fine!

**Comment by nono303** [comment]
hi @qmegas, 
Build process had not change for provided dll, but sources had been "patched" since the "not bugged dll" in Dec 13, 2018   
I just provided binaries from https://github.com/websupport-sk/pecl-memcache sources
I think this kind of bug might be related to sources and not to build process.  
You may open this issue on https://github.com/websupport-sk/pecl-memcache
