### ISSUE TITLE
PHP 7.4.6

### ISSUE THREAD

**Issue by faca5** [nono303/PHP7-memcache-dll#18]
Hello.

Please can you compile for 7.4.6?
php-7.4.x_memcache.dll with php-src 7.4.1

Error:
Warning: PHP Startup: Can't load module 'php_memcache.dll' as it's linked with 14.24, but the core is linked with 14.16 in Unknown on line 0

Thank you.

**Comment by nono303** [comment]
Hi @faca5 
Your error is not related to php-src. 
Your php build is VC15 version and you try to use php-7.4.x_memcache.dll VS16.
So test with https://github.com/nono303/PHP7-memcache-dll/tree/master/vc15 and it'll normally work

**Comment by faca5** [comment]
Hello.
It works.
Thank you!
