### ISSUE TITLE
PHP Warning:  PHP Startup: Can't load module 'C:\php\ext\php_memcache.dll' as it's linked with 14.27, but the core is linked with 14.16 in Unknown on line 0

### ISSUE THREAD

**Issue by mj-ee** [nono303/PHP7-memcache-dll#19]
I downloaded this PHP7 memcache DLL (Memcache Extension (PHP, Thread Safe, x64), but for some unknown reason, even if I put the php_memcache.dll under **c:\php\ext**, and added `extension=php_memcache.dll`, and made sure: `extension_dir="C:\php\ext"`, I still get trouble.

**My Setup:**
- Windows 10 (x64)
- PHP 7.4.10 (Thread Safe, x64) [C:\php]
- Apache 2.4 [C:\Apache]

**> PHP -m**
```
PHP Warning:  PHP Startup: Can't load module 'C:\php\ext\php_memcache.dll' as it's linked with 14.27, but the core is linked with 14.16 in Unknown on line 0

Warning: PHP Startup: Can't load module 'C:\php\ext\php_memcache.dll' as it's linked with 14.27, but the core is linked with 14.16 in Unknown on line 0
```

**From browser:**
`Fatal error: Uncaught Error: Class 'Memcache' not found in C:\www\memcahed.php:17 Stack trace: #0 {main} thrown in C:\www\memcahed.php on line 17`

**Comment by nono303** [comment]
Hi,
Just use vc15 version (14.1) instead of vs16 (14.2)
