### ISSUE TITLE
Please compile with php7.1.5

### ISSUE THREAD

**Issue by sergey144010** [nono303/PHP7-memcache-dll#2]
http://php.net/downloads.php#v7.1.5

**Comment by nono303** [comment]
Hi, 
@sergey144010  : I've tested php-7.1.x_memcache.dll nts x64 provided and it work with php 7.1.5.
Did you have any problem ? if yes, on which version (ts/nts 32/64) ?

**Comment by nono303** [comment]
Hi,
@sergey144010 : Could you please test with the latest php-7.1.x_memcache.dll compiled with php 7.1.8 src and come back if you have any trouble with php 7.1.5.
