### ISSUE TITLE
PHP-memcache-dll for php 8.1

### ISSUE THREAD

**Issue by nc1vr** [nono303/PHP7-memcache-dll#21]
Is there a plan to release memcache DLL module for php 8.1? The latest build 8.1-dev ccf702b for php 8.0 is not compatible with version 8.1 and generates the errors.

**Comment by mtwango** [comment]
When using php-8.0.x_memcache.dll (VS16):
```
Warning: PHP Startup: memcache: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
```

When using php-8.0.x_memcache.dll (VS17):
```
Warning: PHP Startup: Can't load module 'php_memcache.dll' as it's linked with 14.30, but the core is linked with 14.29
```

**Comment by nono303** [comment]
Hi @aimi617, @mtwango 
Just pushed  `php-8.1.x_memcache.dll` for all versions and updated readme to show API number corresponding to PHP version..
Please check if all sounds good for U.

**Comment by mtwango** [comment]
@nono303 Works great, thanks.

**Comment by nc1vr** [comment]
Thanks, it works.
