### ISSUE TITLE
Unable to compile memcache 8 for windows

### ISSUE THREAD

**Issue by nikhell86** [nono303/PHP7-memcache-dll#22]
I am trying to compile memcache for windows with PHP 8.0 

My configure options are:

configure ^
--disable-cli-win32 ^
--disable-debug ^
--disable-embed ^
--disable-ipv6 ^
--disable-phpdbg ^
--disable-phpdbgs ^
--disable-security-flags ^
--disable-test-ini ^
--enable-debug-pack ^
--enable-fd-setsize=2048 ^
--enable-object-out-dir=../build/ ^
--without-analyzer ^
--without-enchant ^
--without-imap ^
--without-snmp ^
--without-ldap ^
--without-oci8 ^
--without-pgsql ^
--without-uncritical-warn-choke ^
--with-toolset=vs ^
--with-cygwin=C:\cygwin64\bin ^
--with-mp=16 ^
--disable-bcmath ^
--disable-brotli ^
--disable-calendar ^
--disable-com-dotnet ^
--disable-ctype ^
--without-dom ^
--disable-filter ^
--without-gd ^
--without-iconv ^
--without-libxml ^
--without-mysqlnd ^
--disable-opcache ^
--disable-phar ^
--without-simplexml ^
--disable-tokenizer ^
--without-xml ^
--disable-xmlwriter ^
--disable-xmlreader ^
--disable-zip ^
--enable-embed ^
--enable-memcache=shared ^
--without-geos ^
--disable-zts ^
--enable-native-intrinsics=sse,sse2,sse3,ssse3,sse4.1,sse4.2,avx ^
--with-mhash ^
--enable-sanitizer

nmake output: 
Microsoft (R) Program Maintenance Utility Version 14.29.30145.0
Copyright (C) Microsoft Corporation.  All rights reserved.
 
Recreating build dirs
Recreating build dirs
Recreating build dirs
        type ext\pcre\php_pcre.def ext\zlib\php_zlib.def > C:\php_sdk\php-dev\vc16\x64\build\Release\php8.dll.def
 
ext\pcre\php_pcre.def
 
 
 
ext\zlib\php_zlib.def
 
 
        "C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64\mc.exe" -h win32\ -r C:\php_sdk\php-dev\vc16\x64\build\Release\ -x C:\php_sdk\php-dev\vc16\x64\build\Release\ win32\build\wsyslog.mc
MC: Compiling win32\build\wsyslog.mc
        "cl.exe" /D COMPILE_DL_MEMCACHE /D MEMCACHE_EXPORTS=1 /D HAVE_MEMCACHE_SESSION=1 /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D WINDOWS=1 /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /D _USE_MATH_DEFINES /FD /wd4996 /Zc:inline /Gw /Zc:__cplusplus /d2FuncCache1 /Zc:wchar_t /MP16 /Zi /LD /MD /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /I "C:\php_sdk\php-dev\vc16\x64\deps\include" /D FD_SETSIZE=2048 /arch:AVX /FoC:\php_sdk\php-dev\vc16\x64\build\Release\pecl\memcache-8.0\src\ /FpC:\php_sdk\php-dev\vc16\x64\build\Release\pecl\memcache-8.0\src\ /FRC:\php_sdk\php-dev\vc16\x64\build\Release\pecl\memcache-8.0\src\ /FdC:\php_sdk\php-dev\vc16\x64\build\Release\pecl\memcache-8.0\src\ /c ..\pecl\memcache-8.0\src\memcache.c ..\pecl\memcache-8.0\src\memcache_ascii_protocol.c ..\pecl\memcache-8.0\src\memcache_binary_protocol.c ..\pecl\memcache-8.0\src\memcache_consistent_hash.c .\pecl\memcache-8.0\src\memcache_pool.c ..\pecl\memcache-8.0\src\memcache_queue.c ..\pecl\memcache-8.0\src\memcache_session.c ..\pecl\memcache-8.0\src\memcache_standard_hash.c
memcache.c
memcache_ascii_protocol.c
memcache_binary_protocol.c
memcache_consistent_hash.c
memcache_pool.c
memcache_queue.c
memcache_session.c
memcache_standard_hash.c
        "cl.exe" /D _USRDLL /D PHP7DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x0601 /D COMPILE_DL_MEMCACHE /Iext/date/lib /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DHAVE_TIMELIB_CONFIG_H=1 /wd4244 /I "ext/hash/sha3/generic64lc" /DHAVE_KECCAKHASH_H=1 /DKeccakP200_excluded /DKeccakP400_excluded /DKeccakP800_excluded /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/pcre/pcre2lib -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /D HAVE_CONFIG_H /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /I "ext/date/lib" /DHAVE_TIMELIB_CONFIG_H=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /D ZLIB_EXPORTS /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D WINDOWS=1 /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /D _USE_MATH_DEFINES /FD /wd4996 /Zc:inline /Gw /Zc:__cplusplus /d2FuncCache1 /Zc:wchar_t /MP16 /Zi /LD /MD /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /I "C:\php_sdk\php-dev\vc16\x64\deps\include" /D FD_SETSIZE=2048 /arch:AVX /FoC:\php_sdk\php-dev\vc16\x64\build\Release\Zend\ /FpC:\php_sdk\php-dev\vc16\x64\build\Release\Zend\ /FRC:\php_sdk\php-dev\vc16\x64\build\Release\Zend\ /FdC:\php_sdk\php-dev\vc16\x64\build\Release\Zend\ /D ZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /d2FuncCache1 /c Zend\zend.c Zend\zend_API.c Zend\zend_alloc.c Zend\zend_ast.c Zend\zend_attributes.c Zend\zend_builtin_functions.c Zend\zend_closures.c Zend\zend_compile.c Zend\zend_constants.c Zend\zend_cpuinfo.c Zend\zend_default_classes.c Zend\zend_exceptions.c Zend\zend_execute.c Zend\zend_execute_API.c Zend\zend_extensions.c Zend\zend_float.c Zend\zend_gc.c Zend\zend_generators.c Zend\zend_hash.c Zend\zend_highlight.c Zend\zend_inheritance.c Zend\zend_ini.c Zend\zend_ini_parser.c Zend\zend_ini_scanner.c Zend\zend_interfaces.c Zend\zend_iterators.c Zend\zend_language_parser.c Zend\zend_language_scanner.c Zend\zend_list.c Zend\zend_llist.c Zend\zend_multibyte.c Zend\zend_object_handlers.c Zend\zend_objects.c Zend\zend_objects_API.c Zend\zend_observer.c Zend\zend_opcode.c Zend\zend_operators.c Zend\zend_ptr_stack.c Zend\zend_smart_str.c Zend\zend_sort.c Zend\zend_stack.c Zend\zend_stream.c Zend\zend_string.c Zend\zend_strtod.c Zend\zend_system_id.c Zend\zend_ts_hash.c Zend\zend_variables.c Zend\zend_virtual_cwd.c Zend\zend_vm_opcodes.c Zend\zend_weakrefs.c
zend.c
zend_API.c
zend_alloc.c
zend_ast.c
zend_attributes.c
zend_builtin_functions.c
zend_closures.c
zend_compile.c
zend_constants.c
zend_cpuinfo.c
zend_default_classes.c
zend_exceptions.c
zend_execute.c
zend_execute_API.c
zend_extensions.c
zend_float.c
zend_gc.c
zend_generators.c
zend_hash.c
zend_highlight.c
zend_inheritance.c
zend_ini.c
zend_ini_parser.c
zend_ini_scanner.c
zend_interfaces.c
zend_iterators.c
zend_language_parser.c
zend_language_scanner.c
zend_list.c
zend_llist.c
zend_multibyte.c
zend_object_handlers.c
zend_objects.c
zend_objects_API.c
zend_observer.c
zend_opcode.c
zend_operators.c
zend_ptr_stack.c
zend_smart_str.c
zend_sort.c
zend_stack.c
zend_stream.c
zend_string.c
zend_strtod.c
zend_system_id.c
zend_ts_hash.c
zend_variables.c
zend_virtual_cwd.c
zend_vm_opcodes.c
zend_weakrefs.c
        "cl.exe" /D _USRDLL /D PHP7DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x0601 /D COMPILE_DL_MEMCACHE /Iext/date/lib /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DHAVE_TIMELIB_CONFIG_H=1 /wd4244 /I "ext/hash/sha3/generic64lc" /DHAVE_KECCAKHASH_H=1 /DKeccakP200_excluded /DKeccakP400_excluded /DKeccakP800_excluded /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/pcre/pcre2lib -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /D HAVE_CONFIG_H /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /I "ext/date/lib" /DHAVE_TIMELIB_CONFIG_H=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /D ZLIB_EXPORTS /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D WINDOWS=1 /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /D _USE_MATH_DEFINES /FD /wd4996 /Zc:inline /Gw /Zc:__cplusplus /d2FuncCache1 /Zc:wchar_t /MP16 /Zi /LD /MD /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /I "C:\php_sdk\php-dev\vc16\x64\deps\include" /D FD_SETSIZE=2048 /arch:AVX /FoC:\php_sdk\php-dev\vc16\x64\build\Release\main\ /FpC:\php_sdk\php-dev\vc16\x64\build\Release\main\ /FRC:\php_sdk\php-dev\vc16\x64\build\Release\main\ /FdC:\php_sdk\php-dev\vc16\x64\build\Release\main\ /c main\SAPI.c main\fopen_wrappers.c main\getopt.c main\internal_functions.c main\main.c main\network.c main\output.c main\php_content_types.c main\php_ini.c main\php_open_temporary_file.c main\php_scandir.c main\php_syslog.c main\php_ticks.c main\php_variables.c main\reentrancy.c main\rfc1867.c main\snprintf.c main\spprintf.c main\strlcat.c main\strlcpy.c
SAPI.c
fopen_wrappers.c
getopt.c
internal_functions.c
main.c
network.c
output.c
php_content_types.c
php_ini.c
php_open_temporary_file.c
php_scandir.c
php_syslog.c
php_ticks.c
php_variables.c
reentrancy.c
rfc1867.c
main\network.c(121): error C2065: 'EAI_SYSTEM': undeclared identifier
main\network.c(121): error C2099: initializer is not a constant
main\network.c(121): warning C4047: 'initializing': 'int' differs in levels of indirection from 'char [13]'
snprintf.c
spprintf.c
strlcat.c
strlcpy.c
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.

**Comment by nono303** [comment]
`EAI_SYSTEM` is not available in MSVC
you must patch _(see https://github.com/nono303/win-build-scripts/blob/master/modules/php-src.patch)_
```
diff --git a/main/network.c b/main/network.c
index 1ad7e370cc..4b7e9d628a 100644
--- a/main/network.c
+++ b/main/network.c
@@ -118,7 +118,9 @@ static const char *php_gai_strerror(int code)
 		{EAI_NONAME, "Name or service not known"},
 		{EAI_SERVICE, "Servname not supported for ai_socktype"},
 		{EAI_SOCKTYPE, "ai_socktype not supported"},
+#  ifdef EAI_SYSTEM
 		{EAI_SYSTEM, "System error"},
+#  endif
 		{0, NULL}
 	};
 	int i;
```

**Comment by nikhell86** [comment]
After making this change getting this:

---------------------------------------
|                   |                 |
---------------------------------------
| Build type        | Release         |
| Thread Safety     | No              |
| Compiler          | Visual C++ 2019 |
| Architecture      | x64             |
| Optimization      | PGO disabled    |
| Native intrinsics | AVX             |
| Static analyzer   | disabled        |
---------------------------------------


WARNING
The following arguments is invalid, and therefore ignored:
 --disable-brotli
 --without-geos


Type 'nmake' to build PHP

c:\php_sdk\php-dev\vc16\x64\php-8.0.20-src
$ nmake

Microsoft (R) Program Maintenance Utility Version 14.29.30145.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Recreating build dirs
Recreating build dirs
Recreating build dirs
php8.dll.def : error LNK2001: unresolved external symbol adler32
php8.dll.def : error LNK2001: unresolved external symbol compress
php8.dll.def : error LNK2001: unresolved external symbol compress2
php8.dll.def : error LNK2001: unresolved external symbol compressBound
php8.dll.def : error LNK2001: unresolved external symbol crc32
php8.dll.def : error LNK2001: unresolved external symbol deflate
php8.dll.def : error LNK2001: unresolved external symbol deflateBound
php8.dll.def : error LNK2001: unresolved external symbol deflateCopy
php8.dll.def : error LNK2001: unresolved external symbol deflateEnd
php8.dll.def : error LNK2001: unresolved external symbol deflateInit2_
php8.dll.def : error LNK2001: unresolved external symbol deflateInit_
php8.dll.def : error LNK2001: unresolved external symbol deflateParams
php8.dll.def : error LNK2001: unresolved external symbol deflatePrime
php8.dll.def : error LNK2001: unresolved external symbol deflateReset
php8.dll.def : error LNK2001: unresolved external symbol deflateSetDictionary
php8.dll.def : error LNK2001: unresolved external symbol get_crc_table
php8.dll.def : error LNK2001: unresolved external symbol gzclearerr
php8.dll.def : error LNK2001: unresolved external symbol gzclose
php8.dll.def : error LNK2001: unresolved external symbol gzdopen
php8.dll.def : error LNK2001: unresolved external symbol gzeof
php8.dll.def : error LNK2001: unresolved external symbol gzerror
php8.dll.def : error LNK2001: unresolved external symbol gzflush
php8.dll.def : error LNK2001: unresolved external symbol gzfwrite
php8.dll.def : error LNK2001: unresolved external symbol gzgetc
php8.dll.def : error LNK2001: unresolved external symbol gzgets
php8.dll.def : error LNK2001: unresolved external symbol gzopen
php8.dll.def : error LNK2001: unresolved external symbol gzprintf
php8.dll.def : error LNK2001: unresolved external symbol gzputc
php8.dll.def : error LNK2001: unresolved external symbol gzputs
php8.dll.def : error LNK2001: unresolved external symbol gzread
php8.dll.def : error LNK2001: unresolved external symbol gzrewind
php8.dll.def : error LNK2001: unresolved external symbol gzseek
php8.dll.def : error LNK2001: unresolved external symbol gzsetparams
php8.dll.def : error LNK2001: unresolved external symbol gztell
php8.dll.def : error LNK2001: unresolved external symbol gzungetc
php8.dll.def : error LNK2001: unresolved external symbol gzwrite
php8.dll.def : error LNK2001: unresolved external symbol inflate
php8.dll.def : error LNK2001: unresolved external symbol inflateBack
php8.dll.def : error LNK2001: unresolved external symbol inflateBackEnd
php8.dll.def : error LNK2001: unresolved external symbol inflateBackInit_
php8.dll.def : error LNK2001: unresolved external symbol inflateCopy
php8.dll.def : error LNK2001: unresolved external symbol inflateEnd
php8.dll.def : error LNK2001: unresolved external symbol inflateInit2_
php8.dll.def : error LNK2001: unresolved external symbol inflateInit_
php8.dll.def : error LNK2001: unresolved external symbol inflateReset
php8.dll.def : error LNK2001: unresolved external symbol inflateReset2
php8.dll.def : error LNK2001: unresolved external symbol inflateSetDictionary
php8.dll.def : error LNK2001: unresolved external symbol inflateSync
php8.dll.def : error LNK2001: unresolved external symbol inflateSyncPoint
php8.dll.def : error LNK2001: unresolved external symbol inflateValidate
php8.dll.def : error LNK2001: unresolved external symbol uncompress
php8.dll.def : error LNK2001: unresolved external symbol zError
php8.dll.def : error LNK2001: unresolved external symbol zlibCompileFlags
php8.dll.def : error LNK2001: unresolved external symbol zlibVersion
C:\php_sdk\php-dev\vc16\x64\build\Release\php8.lib : fatal error LNK1120: 54 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.

Also I downloaded TS source for php, why its says Thread Safe: NO

**Comment by nono303** [comment]
Have you a functional MSVC compile of PHP **without** memcache extension?

**Comment by nikhell86** [comment]
Yes i did that:

configure --disable-all --enable-cli --enable-$remains
PHP Version: 8.0.20

Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
  Detected compiler Visual C++ 2019
  Detected 64-bit compiler
Checking for link.exe ...  <in default path>
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
  Detected bison version 3.3.2
Checking for sed.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
  Detected re2c version 1.1.1
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <in default path>
Checking for 7za.exe ...  <in default path>
Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64
Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64
Enabling multi process build

Build dir: C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS
PHP Core:  php8ts.dll and php8ts.lib

Checking for wspiapi.h ...  <in default path>
Enabling IPv6 support
Enabling SAPI sapi\cli
Checking for library edit_a.lib;edit.lib ... <not found>
Enabling extension ext\date
Enabling extension ext\hash
Checking for KeccakHash.h ...  ext/hash/sha3/generic64lc
Enabling extension ext\json
Enabling extension ext\pcre
Enabling extension ext\reflection
Enabling extension ext\spl
Checking for timelib_config.h ...  ext/date/lib
Enabling extension ext\standard

Creating build dirs...
Generating files...
Generating Makefile
Generating main/internal_functions.c
Generating main/config.w32.h
Generating phpize
Done.



Enabled extensions:
-----------------------
| Extension  | Mode   |
-----------------------
| date       | static |
| hash       | static |
| json       | static |
| pcre       | static |
| reflection | static |
| spl        | static |
| standard   | static |
-----------------------


Enabled SAPI:
-------------
| Sapi Name |
-------------
| cli       |
-------------


---------------------------------------
|                   |                 |
---------------------------------------
| Build type        | Release         |
| Thread Safety     | Yes             |
| Compiler          | Visual C++ 2019 |
| Architecture      | x64             |
| Optimization      | PGO disabled    |
| Native intrinsics | SSE2            |
| Static analyzer   | disabled        |
---------------------------------------


WARNING
The following arguments is invalid, and therefore ignored:
 --enable-$remains


Type 'nmake' to build PHP

C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src
$ nmake

Microsoft (R) Program Maintenance Utility Version 14.29.30145.0
Copyright (C) Microsoft Corporation.  All rights reserved.

SAPI.c
fopen_wrappers.c
getopt.c
internal_functions.c
main.c
network.c
output.c
php_content_types.c
php_ini.c
php_open_temporary_file.c
php_scandir.c
php_syslog.c
php_ticks.c
php_variables.c
reentrancy.c
rfc1867.c
snprintf.c
spprintf.c
strlcat.c
strlcpy.c
   Creating library C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS\php8ts.lib and object C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS\php8ts.exp
   Creating library C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS\php.lib and object C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS\php.exp
SAPI sapi\cli build complete

C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src
$ configure --disable-all --enable-cli --enable-memcache --enable-session
PHP Version: 8.0.20

Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
  Detected compiler Visual C++ 2019
  Detected 64-bit compiler
Checking for link.exe ...  <in default path>
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
  Detected bison version 3.3.2
Checking for sed.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
  Detected re2c version 1.1.1
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <in default path>
Checking for 7za.exe ...  <in default path>
Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64
Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64
Enabling multi process build

Build dir: C:\php_sdk\php-dev\vc16\x64\php-8.0.20-src\x64\Release_TS
PHP Core:  php8ts.dll and php8ts.lib

Checking for wspiapi.h ...  <in default path>
Enabling IPv6 support
Enabling SAPI sapi\cli
Checking for library edit_a.lib;edit.lib ... <not found>
Enabling extension ext\date
Enabling extension ext\hash
Checking for KeccakHash.h ...  ext/hash/sha3/generic64lc
Enabling extension ext\json
Enabling extension ext\pcre
Enabling extension ext\reflection
Enabling extension ext\session
Enabling extension ext\spl
Checking for timelib_config.h ...  ext/date/lib
Enabling extension ext\standard
Enabling extension ..\pecl\memcache-8.0\src

Creating build dirs...
Generating files...
Generating Makefile
Generating main/internal_functions.c
Generating main/config.w32.h
Generating phpize
Done.

**Comment by nono303** [comment]
...not sure to understand what you are doing in your sequence without nmake after second configure...
```
configure --disable-all --enable-cli --enable-memcache=shared --enable-session --enable-zlib
nmake
```
if you satisfy all include & lib required in your deps folder you should have the same result as this: [php_vs17-x64-avx_2022-06-11_14-49-28.log](https://github.com/nono303/PHP-memcache-dll/files/8883956/php_vs17-x64-avx_2022-06-11_14-49-28.log)
