### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'ext\php_memcache.dll' - The specified module could not be found.

### ISSUE THREAD

**Issue by dca00** [nono303/PHP7-memcache-dll#23]
From my PHP info:

PHP Version 7.0.6
Compiler | MSVC14 (Visual C++ 2015)
Architecture | x64

I tried php-7.0.x_memcache.dll and php-7.1.x_memcache.dll but both throw the same warning in subject.

deplister says that they have all of the necessary DLLs:

C:\Program Files\PHP\ext>..\deplister.exe php_memcache.dll
php7ts.dll,OK
WS2_32.dll,OK
VCRUNTIME140.dll,OK
api-ms-win-crt-heap-l1-1-0.dll,OK
api-ms-win-crt-convert-l1-1-0.dll,OK
api-ms-win-crt-string-l1-1-0.dll,OK
api-ms-win-crt-stdio-l1-1-0.dll,OK
api-ms-win-crt-utility-l1-1-0.dll,OK
api-ms-win-crt-runtime-l1-1-0.dll,OK
api-ms-win-crt-time-l1-1-0.dll,OK
KERNEL32.dll,OK

What is missing?

**Comment by nono303** [comment]
hi @dca00,
In your configuration, you must use https://github.com/nono303/PHP-memcache-dll/blob/master/vc14/x64/ts/php-7.0.x_memcache.dll
If it's still fail loading with message "he specified module could not be found", as your dll dependencies seems to be OK, you'll need to catch the root cause of this failure in windows event logs, WER or [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) to understand why loading failed.

**Comment by dca00** [comment]
There is no extra information in the event log:

The following information was included with the event: 

php[60896]
PHP Warning: PHP Startup: Unable to load dynamic library 'ext\php_memcache.dll' - The specified module could not be found.
 ("C:\Apache24\bin\httpd.exe" -k runservice)


I am not familiar with procdump. Can you suggest its command line or further actions once the dump is created?

**Comment by nono303** [comment]
Ok. 
what happens when you launch from cmdline:
> php -m
> php -v

https://docs.microsoft.com/en-us/sysinternals/downloads/procdump
> Register as the Just-in-Time (AeDebug) debugger. Makes full dumps in c:\dumps:
> `C:\>procdump -ma -i c:\dumps`

**Comment by dca00** [comment]
```
[PHP Modules]
bcmath
bz2
calendar
com_dotnet
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]
```

```
PHP 7.0.6 (cli) (built: Apr 28 2016 13:46:50) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by dca00** [comment]
```
C:\Program Files (x86)\SysinternalsSuite>procdump -ma -i c:\dumps
No process matching the specified name is running.
```

**Comment by nono303** [comment]
I see that memcache is well loaded when you run php out of httpd (considering that you don't have any red windows popup when executing php -m)
In this case we can be sure that **you use the good php_memcache.dll version** BUT in an httpd sapi context, it can't be loaded...
my assumption are :
1) a path difference/issue on httpd service
2) an dll overrriding betwen httpd and php /bin folder in path

**Comment by dca00** [comment]
You are right, it was a path problem!
This can be marked solved.
Much appreciated!

**Comment by dca00** [comment]
Now, I tried to upgrade PHP to 7.4 but faced the same error.
This time I am confused. From phpinfo:

Compiler: MSVC14 (Visual C++ 2015) 

It looks like you only have MSVC15 version of php-7.4.x_memcache.dll.

**Comment by nono303** [comment]
> It looks like you only have MSVC15 version of php-7.4.x_memcache.dll.

Yes, VC14 had been discontinued for php >= 7.2

**Comment by dca00** [comment]
Could you by any chance do a VC15 build for 7.4 with AVX?
This is the combination of Apache 2.4.54 with PHP 7.4

**Comment by nono303** [comment]
this one is the VC15 x64 ThreadSafe version for php 7.4 https://github.com/nono303/PHP-memcache-dll/blob/master/vc15/x64/ts/php-7.4.x_memcache.dll
it's compiled with SSE2 instructions as AVX doesn't change anything for php_memcache ext

**Comment by dca00** [comment]
This one worked. Thank you! Not sure how I missed it.
But amazingly it only worked after I added .dll after the extension as in
`extension=php_memcache.dll`
Until then it threw an error: File not found. A stack exchange comment about the same poblem hinted at this.

**Comment by nono303** [comment]
real file naming mandatory in extension of php.ini came since 7.4 if I remember....
