### ISSUE TITLE
Can't seem to find a version that works...

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#24]
Hello, sorry to bother you.
I'm trying to get php_memcache.dll for php 7.4.30, php 8.0.21 & php 8.1.8
When I add it to our php package and then run it I'm getting the following error..
![image](https://user-images.githubusercontent.com/1850089/182925652-554e2023-7709-4984-a47e-94dce44aa3a6.png)
We use it as part of http://github.com/Bearsampp/Bearsampp in our module_php package.
I used the vc17 x64 TS build.

**Comment by nono303** [comment]
Hi @N6REJ 
You might have a look on `AVX` version (see https://github.com/nono303/PHP-memcache-dll#how-to-get-the-good-version)

**Comment by N6REJ** [comment]
I tried the tutorial on how to find the right version but "grep" doesn't work in windows 10
Created a PR as I found the method for windows

**Comment by N6REJ** [comment]
still having the same issue with the 8.x versions.  4.7 works fine for php 7.4 but 8.x doesn't.

**Comment by N6REJ** [comment]
update:  VC15 worked.  Neither of the "VS16" nor "VS17" work.

**Comment by N6REJ** [comment]
update: memcache only works on 7.4.30 not php 8.0.21 or 8.1.8  The module never loads with 8.x+

**Comment by RobiNN1** [comment]
You must have correct version. It works fine on my Laragon localhost - `php-8.1.9-Win32-vs16-x64` and https://github.com/nono303/PHP-memcache-dll/blob/master/vs16/x64/ts/php-8.1.x_memcache.dll

**Comment by N6REJ** [comment]
I have no idea what I did wrong but the file you just gave me does infact work!
TY TY TY TY
