### ISSUE TITLE
Php 8.1.8 & 8.1.10 won't load memcache

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#27]
I'm very confused again.
When I try to use memcache on either php 8.1.8 or 8.1.10 I get the following...
![image](https://user-images.githubusercontent.com/1850089/188581081-7209de77-f2b4-4b93-841b-6c6180e63e53.png)
using https://github.com/nono303/PHP-memcache-dll/raw/master/vs16/x64/ts/avx/php-8.1.x_memcache.dll
when I use php 8.1.9 I get
![image](https://user-images.githubusercontent.com/1850089/188581444-1b76a1a3-42f7-42f7-8dbb-084ca7edc8eb.png)

What is it trying to tell me?

**Comment by nono303** [comment]
Hi @N6REJ 
First screenshot mean that you are using VC15 memchache dll on VS16 php exe **that will never work**
Second screenshot mean that you are using both memchache dll & php exe vs16 compiled (MSVC2019 == VS16)
Clear for U?

**Comment by N6REJ** [comment]
ah, ok.. I'll trying fixing that and get back to you.  TY!

**Comment by N6REJ** [comment]
That fixed everything... TY!
What do we do about modules like imagick who haven't released vs16 variants?

**Comment by nono303** [comment]
https://mlocati.github.io/articles/php-windows-imagick.html have vs16 compiled
Otherwise U might compile it ;)

**Comment by N6REJ** [comment]
thats the wrong one.  I need "imagemagick"  which I find here ... https://windows.php.net/downloads/pecl/deps/
perhaps someday you could teach us how to compile our own so we're not so dependent on others

**Comment by nono303** [comment]
> perhaps someday you could teach us how to compile our own so we're not so dependent on others

All is here https://github.com/nono303/win-build-scripts
