### ISSUE TITLE
php 8.0.23 breaks memcache

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#28]
Apparently the new release breaks memcache for 8.0.23 ( haven't tried others. )
we get the ajax spinner which means it can't read its status.
we're using https://github.com/nono303/PHP-memcache-dll/blob/master/vs16/x64/ts/avx/php-8.0.x_memcache.dll
even tried the version that we know works with 8.0.22 and it fails too

**Comment by nono303** [comment]
As released version 8.1.0.103 integrate PR not yet validated (see https://github.com/nono303/PHP-memcache-dll#version-810103-branch-non_blocking_io_php8) it might have impact / regression depending on how you use it.
Particulary https://github.com/websupport-sk/pecl-memcache/pull/101

**Comment by N6REJ** [comment]
I'm sorry to be dumb but idk what that means.  
Are you saying its not ready for 8.0.23?
if so, rough eta?

**Comment by nono303** [comment]
nothing to deal with php version, PR applied to pecl-memcache had error regressions.
I just deleted this new release until PR will be merged in official repo

**Comment by nono303** [comment]
I'll release latest stable version : 8.0.1 "[96910ce](https://github.com/websupport-sk/pecl-memcache/commit/96910ce9c4b59733d94162f422918256fe738e83)" tomorrow
