### ISSUE TITLE
Errors for latest php releases

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#29]
Getting the following
![image](https://user-images.githubusercontent.com/1850089/215918151-d6557382-b738-41d1-859e-d7462419b796.png)
we used the vc16 avx ts version

**Comment by nono303** [comment]
Hi @N6REJ 
checked latest vc16 avx ts: works fine with php-8.2.x_memcache.dll both x64 & x86 on standard php windows builds.
"bad image" might be an issue dealing with 
 - x86 & x64 mix 
 - msvc redist missing
 - avx not supported by processor
 
see https://github.com/nono303/PHP-memcache-dll#how-to-get-the-good-version
