### ISSUE TITLE
PHP 8.3 release

### ISSUE THREAD

**Issue by nc1vr** [nono303/PHP7-memcache-dll#31]
Is any plan to prepare memcache DLL for PHP 8.3? Today was released a major stable version PHP 8.3.

**Comment by nono303** [comment]
Hi @aimi617 
Done: https://github.com/nono303/PHP-memcache-dll/commit/731897436cb0e1317672683ab7ef1cc42e06a636
I'll let you check that all work for U

**Comment by nc1vr** [comment]
I downloaded AVX version, have to test 8.3 thoroughly. If any issues I'll let you know, thanks.
