### ISSUE TITLE
latest release throws windows error.

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#32]
I'm getting the following error when I try to use the new 8.3 beta release
<img width="317" alt="image" src="https://github.com/nono303/PHP-memcache-dll/assets/1850089/52d1b265-0921-44cf-b56b-fa274da00580">
I'm using vs16/ts and tried both avx and non.

**Comment by nono303** [comment]
Hi @N6REJ,
You try to use 8.3 but your error message show a path named **8.2** witch are not with the same API.
Same comment as for your last issues : https://github.com/nono303/PHP-memcache-dll#how-to-get-the-good-version

**Comment by N6REJ** [comment]
I dl'd the memcache for 8.1, 8.2 & 8.3 from https://github.com/nono303/PHP-memcache-dll/releases/tag/8.2-972b554 and also tried from https://github.com/nono303/PHP-memcache-dll/tree/8.2-972b554/vs16/x64/ts & https://github.com/nono303/PHP-memcache-dll/tree/8.2-972b554/vs16/x64/ts/avx  I'm getting the same results with all 3 of the new php versions https://github.com/Bearsampp/modules-untouched/releases/tag/2023.12.31

**Comment by nono303** [comment]
- could you export `php -i` in a txt file and result of `sigcheck -q php-8.3.x_memcache.dll` of each couple of file which failed?
- have you more detailed error in eventlog ?

**Comment by N6REJ** [comment]
sorry for the delay getting back to you.  For 8.1.27 I got the following...
<img width="560" alt="image" src="https://github.com/nono303/PHP-memcache-dll/assets/1850089/5db1de14-63ca-42ba-9e4a-54725414f211">
[8.1.27.txt](https://github.com/nono303/PHP-memcache-dll/files/13834293/8.1.27.txt)

to put that in comparison with 8.1.23 which works. 
<img width="990" alt="image" src="https://github.com/nono303/PHP-memcache-dll/assets/1850089/8eb5325e-613b-49c1-b4a5-b1686f963c9a">

[8.1.23.txt](https://github.com/nono303/PHP-memcache-dll/files/13834342/8.1.23.txt)

**Comment by nono303** [comment]
Hi @N6REJ 
1. I really don’t understand why you are trying to use php-8.3.x_memcache.dll as your php version is 8.1!
2. I don’t know what is the file of your first screenshoot (`sigcheck -q php_memcache.dll` for **8.1.27**) as file date fo `2024-01-01` correspond to nothing from my repo (last commit `2023-11-24`) & dll properties are all to n/a _(maybe not even a dll ^^)_
3. `sigcheck -q php_memcache.dll` for **8.1.23** show the good and latest file **you MUST use** for your system : **php 8.1.x vs16 x64 ts**
See [https://github.com/nono303/PHP-memcache-dll/blob/master/bininfo.csv l.104](https://github.com/nono303/PHP-memcache-dll/blob/master/bininfo.csv%20l.104) which **EXACTLY correspond your second screenshot**
`/vs16/x64/ts/php-8.1.x_memcache.dll;22/09/2022 21:15;64;ltcg;;14.29;8.0.1.0;8.0.1;8.0.1;php-8.1.x_memcache.pdb;OK;OK;php:php_memcache; ;arch:x64 vcver:14.29[vs16] commit:96910ce tag:8.0.1 branch:NON_BLOCKING_IO_php8 date:2022-07-29 php:8.1 build:ts;php_memcache.dll;php_memcache.dll;https://github.com/nono303/win-build-scripts`

All might be quite well documented to avoid this kind of redundant non-issue: #30 #29 #27 #26 #24 related to your environment / configuration and not to the provided binary.
If some part of the documentation is not clear / understandable don’t hesitate to make a PR, but understand that **this repo is not designed to provide support for specific prodcut** like Bearsampp

**Comment by N6REJ** [comment]
> Hi @N6REJ
> 
> 1. I really don’t understand why you are trying to use php-8.3.x_memcache.dll as your php version is 8.1!  I also downloaded them individually as previously stated.

Thats where your confused.  In that pr there are all the .dll's.  I'm using the 8.1 one for 8.1, 8.2 for 8.2 etc.

>I don’t know what is the file of your first screenshoot (sigcheck -q php_memcache.dll for 8.1.27) as file date fo 2024-01-01 correspond to nothing from my repo (last commit 2023-11-24) & dll properties are all to n/a (maybe not even a dll ^^)

The file date is going to change because the file has been renamed.

I will reread thru the documentation and triple check the files used.

**Comment by nono303** [comment]
You are mixing `php_memcache` & `php` version which are totally uncorrelated.
Can you detail what is confusing in my [README.md](https://github.com/nono303/PHP-memcache-dll/blob/master/README.md)

![image](https://github.com/nono303/PHP-memcache-dll/assets/2869665/7b5ff63b-5ee4-4914-aa56-b339b5d09349)

if you don't understand that php_memcache 8.2 is built for PHP 8.2 & PHP 8.3 / php_memcache 8.0.1 is built for PHP 8.1 & PHP 8.0, please **make a PR to purpose a clarification**

⏩ I didn't build php_memcache 8.2 for php 8.1 as this php version is deprecated is not actively supported since 25 Nov 2023

**Comment by N6REJ** [comment]
I discovered what the root problem has been.  Somehow the filesize that I see in your git doesn't match that when i've saved it in my download folder so then it doesn't match the file size in git.  Fixing that fixed the issue.  your sigcheck helped me find that out.

**Comment by N6REJ** [comment]
I just now caught this that you wrote.  I'm going to show it to my partner and see if its just my old brain or not
![image](https://github.com/nono303/PHP-memcache-dll/assets/1850089/a917ce28-bdf3-46a3-a8ce-5d20355c21b2)
