### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by dolenec** [nono303/PHP7-memcache-dll#35]
Checked and can not find VS19 build...

[23-Jan-2024 10:40:22 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_memcached.dll' (tried: ***RESTRICTED***\php_memcached.dll (The specified module could not be found)

![slika](https://github.com/nono303/PHP-memcache-dll/assets/16633222/79d52f53-d919-4cd0-9647-a2f831ff3fd7)

So, where to find correct .dll for 8.1.27 PHP?

Thank you for answer..

**Comment by nono303** [comment]
Hi @dolenec,
vs19 doesn’t exist 😊 it’s vs16 in your case (from `PHP Extension build`) 
So for you, according to `phpinfo()`
**vs16 x64 nts 8.1** correspond to https://github.com/nono303/PHP-memcache-dll/blob/master/vs16/x64/nts/php-8.1.x_memcache.dll
