### ISSUE TITLE
Don't understand instructions

### ISSUE THREAD

**Issue by N6REJ** [nono303/PHP7-memcache-dll#36]
I've followed your instructions very carefully and even made sure msvc is 2015-2022 and I still get
```
> php -i | findstr Compiler
Compiler => Visual C++ 2019
```
which doesn't match your instructions.  I'm so confused.  I still can't get memcache to stop saying its not a windows dll
This is the code I'm using https://github.com/nono303/PHP-memcache-dll/blob/master/vs16/x64/ts/php-8.3.x_memcache.dll

**Comment by nono303** [comment]
...still mixing php_memcache & php version
according to https://github.com/nono303/PHP-memcache-dll/issues/32#issuecomment-1879601685 use https://github.com/nono303/PHP-memcache-dll/blob/master/vs16/x64/ts/php-8.1.x_memcache.dll and keep it for php 8.1

**Comment by N6REJ** [comment]
but what about php 8.3?

**Comment by N6REJ** [comment]
When I see Visual c++ 2019 thats vs16?

**Comment by nono303** [comment]
Seriously? 
https://github.com/nono303/PHP-memcache-dll?tab=readme-ov-file#how-to-get-the-good-version
![image](https://github.com/nono303/PHP-memcache-dll/assets/2869665/a8725f5f-1d8e-46b4-8bea-36418791c5a3)
