### ISSUE TITLE
i am using this dll for php 7 version on xampp This is not woking

### ISSUE THREAD

**Issue by taslimwaris** [nono303/PHP7-memcache-dll#4]
Hi ,
I am using Xampp PHP Version 7.2.3.
Please see bloe my steps
1.I had installed memcached-win64-1.4.4-14 by this into my C drive:
2.in php.ini put this
extension=php-7.1.x_memcache.dll
[Memcache]
memcache.allow_failover = 1
memcache.max_failover_attempts=20
memcache.chunk_size =8192
memcache.default_port = 11211

3.in xampp\php\ext folder i put=> php-7.1.x_memcache.dll
4. by command prompt run this command memcached.exe -d start
5. Restart xampp

but this is not showing in my phpinfo.

Please help.

Thanks & Regards
Taslim Waris

**Comment by Sn0wCrack** [comment]
>Xampp PHP Version 7.2.3.

>php-7.1.x_memcache.dll

This might be your issue, try using the php-7.2.x-memcache.dll

**Comment by taslimwaris** [comment]
ye i know this is my issue i need help from you can you help
