### ISSUE TITLE
VC15 x86 PHP 7.2 DLL file not working.

### ISSUE THREAD

**Issue by sarvap-praharanayuthan** [nono303/PHP7-memcache-dll#6]
`vc15\x86\ts\php-7.2.x_memcache.dll` does not work. The Apache process does not start with it. Now downgraded the PHP version to 7.1.20 to use VC14 version. Now using `vc14\x86\ts\php-7.1.x_memcache.dll`

**Comment by juongithub** [comment]
I have the same problem, here is the event viewer log:
Faulting application name: php.exe, version: 7.2.9.0, time stamp: 0x5b74b889
Faulting module name: php-7.2.x_memcache.dll, version: 3.0.9.0, time stamp: 0x5b756ba4
Exception code: 0xc000001d
Fault offset: 0x00005651
Faulting process id: 0x243c
Faulting application start time: 0x01d4409702da8ee8
Faulting application path: C:\xampp\php\php.exe
Faulting module path: C:\xampp\php\ext\php-7.2.x_memcache.dll
Report Id: 413acaee-487e-4430-b269-66a932650f10
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pfugwtg** [comment]
I have the same problem:
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_memcache.dll' (tried: D:/Programs/PHP/php-7.2.0-Win32-VC15-x64/ext\php_memcache.dll

**Comment by juongithub** [comment]
@pfugwtg probably the problem you are reporting is not related to the others, it seems you have used the wrong DLL for your PHP version.

**Comment by juongithub** [comment]
just to add more info, the same happens with the PHP build in **PHP Windows ''performance'' builds**.

**Comment by nono303** [comment]
same as #8
