### ISSUE TITLE
HTTP ERROR 500 using php-7.2.x_memcache.dll in windows server 2008 r2/msvc15/iis7.5/php7.2.9

### ISSUE THREAD

**Issue by rewalax** [nono303/PHP7-memcache-dll#7]
when i add this extension in php.ini, it will throw an error "HTTP ERROR 500.0 - Internal Server Error( FastCGI process quit unexpectedly )"
can you pls fix it or tell me how to do. thank u very much.
my env: windows server 2008 r2/msvc15/iis7.5/php7.2.9,using php-7.2.x_memcache.dll.

**Comment by nono303** [comment]
same as #8
