### ISSUE TITLE
If your dll is included in php.ini, php fails to start

### ISSUE THREAD

**Issue by tsimmons** [nono303/PHP7-memcache-dll#8]
There are several issues raised similar to this but I'm opening my own to include more details. Using PHP x64 7.2.10 on Windows 2008 R2; If I include a call in php.ini to load your dll from http://windows.php.net/downloads/php-sdk/deps/vc15/x64/

    extension=php_memcache.dll

Then try simply running

    php.exe --info

I get the following errors in the application event log:

```
Faulting application name: php.exe, version: 7.2.10.0, time stamp: 0x5b99b3fb
Faulting module name: php_memcache.dll, version: 3.0.9.0, time stamp: 0x5b97b12c
Exception code: 0xc000001d
Fault offset: 0x0000000000006882
Faulting process id: 0x69c
Faulting application start time: 0x01d44f8b6b34dd6c
Faulting application path: d:\php\php.exe
Faulting module path: D:\PHP\ext\php_memcache.dll
Report Id: a9c40fbc-bb7e-11e8-8589-0026b97b6554
```
Followed by the following error

```
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program CLI because of this error.

Program: CLI
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0
```
Then one more event

```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: php.exe
P2: 7.2.10.0
P3: 5b99b3fb
P4: php_memcache.dll
P5: 3.0.9.0
P6: 5b97b12c
P7: c000001d
P8: 0000000000006882
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\username\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_php.exe_3c1e8d33edec1cd71dfe4262d8eff8ea3d18d93_61ae4cfe

Analysis symbol: 
Rechecking for solution: 0
Report Id: a9c40fbc-bb7e-11e8-8589-0026b97b6554
Report Status: 4
```
Any recommendations or something else to try? This seems to be our last holdup preventing upgrading from PHP 5.6 to PHP 7.2. @nono303 ?

Edit: This is using the nts version and the PHP from https://windows.php.net/download/

Thanks &
Cheers,

Toby

**Comment by nono303** [comment]
Hi @tsimmons !
What MSVC redist version is installed on your system ?

**Comment by tsimmons** [comment]
~~I installed VCRT 15.~~ I finally just downloaded Visual Studio Express and compiled my own on 2008 R2, with all your same patches to memcache and it is working for me. Still curious as to why yours does not.

Edit: Please see my reply below with corrected information.

**Comment by nono303** [comment]
According to https://github.com/nono303/PHP7-memcache-dll/blob/master/README.md I actually see two main explanations for all 5xx errors or app crash:

- your cpu doesn't support AVX instruction
- your msvc redist is under 14.15.x version

@tsimmons @matak @sarvap-praharanayuthan @juongithub @pfugwtg @rewalax Please give me some feedback about these two hypotheses!

**Comment by nono303** [comment]
note for cpu AVX test use https://docs.microsoft.com/fr-fr/sysinternals/downloads/coreinfo ex.

```
C:\Windows\System32>coreinfo | grep AVX

Coreinfo v3.31 - Dump information on system CPU and memory topology
Copyright (C) 2008-2014 Mark Russinovich
Sysinternals - www.sysinternals.com
AVX             *       Supports AVX intruction extensions
```

**Comment by juongithub** [comment]
My CPU does not support AVX instruction extensions. Last version of MSVC redist installed on my system is 14.0.24215.1

**Comment by tsimmons** [comment]
Strike my previous answer; Just checked the registry and the version from

    HKLM\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64

v14.15.26706.00; also, my CPUs (four computers, one physical, two esxi VMs and one AWS instance) all support AVX instruction. What else can we check?

**Comment by juongithub** [comment]
Installed MSVC redist 14.15.26706.0 but nothing changed. Just checked on another machine with MSVC redist 14.15.26706.0 but with AVX and it worked.

**Comment by juongithub** [comment]
Installed MSVC redist 14.15.26706.0 but nothing changed. Just checked on another machine with MSVC redist 14.15.26706.0 but with AVX and it worked (however this CPU has many differences with mine). Also tried to uninstall MSVC redist 14.15.26706.0 and it worked on the CPU with AVX. (all tests with x86)

**Comment by nono303** [comment]
Thanks @juongithub!
So, I’ve just push AVX and standard build for x86 x64 TS & NTS versions.
Could you please test the standard build and tell me if all is now OK?

**Comment by tsimmons** [comment]
The new dll in

    https://github.com/nono303/PHP7-memcache-dll/tree/master/vc15/x64/nts

works fine. The one in

    https://github.com/nono303/PHP7-memcache-dll/tree/master/vc15/x64/nts/avx

does not. Seems odd that my CPUs claim to have AVX (Edit, see command)

```
D:\PHP>coreinfo | findstr AVX

Coreinfo v3.31 - Dump information on system CPU and memory topology
Copyright (C) 2008-2014 Mark Russinovich
Sysinternals - www.sysinternals.com
AVX             -       Supports AVX intruction extensions
```
but that build doesn't work.

Either way, it appears the standard build sorts it for me. Thanks! I'll wait a day or two before closing this issue, unless you want me to do otherwise. Thanks again @nono303 !

**Comment by juongithub** [comment]
> Thanks @juongithub!
> So, I’ve just push AVX and standard build for x86 x64 TS & NTS versions.
> Could you please test the standard build and tell me if all is now OK?

### My machine
vc15/x86/ts/php-7.2.x_memcache.dll does not work (PHP Startup: Unable to load dynamic library)
vc15/x86/ts/avx/php-7.2.x_memcache.dll does not work (as expected)*
vc15/x86/ts/avx/php-7.2.x_memcache.dll works after copying **php7ts.dll** to **php7.dll**

### Machine with AVX
vc15/x86/ts/php-7.2.x_memcache.dll does not work (PHP Startup: Unable to load dynamic library)
vc15/x86/ts/avx/php-7.2.x_memcache.dll  works as expected*
vc15/x86/ts/avx/php-7.2.x_memcache.dll works after copying **php7ts.dll** to **php7.dll**

*the DLL has a dependency with **php7.dll** and not with **php7ts.dll**, just copied **php7ts.dll** to **php7.dll** and it worked.

**Comment by juongithub** [comment]
```
> D:\PHP>coreinfo | findstr AVX
> 
> Coreinfo v3.31 - Dump information on system CPU and memory topology
> Copyright (C) 2008-2014 Mark Russinovich
> Sysinternals - www.sysinternals.com
> AVX             -       Supports AVX intruction extensions

```
this means your CPU does not support AVX.

**Comment by tsimmons** [comment]
> ```
> > D:\PHP>coreinfo | findstr AVX
> > 
> > Coreinfo v3.31 - Dump information on system CPU and memory topology
> > Copyright (C) 2008-2014 Mark Russinovich
> > Sysinternals - www.sysinternals.com
> > AVX             -       Supports AVX intruction extensions
> ```
> this means your CPU does not support AVX.

Oh, duh. The dash instead of an asterisk, I supposed. Okay, I'm gonna consider this issue closed. Thanks for the standard build @nono303!
