### ISSUE TITLE
Warning: PHP Startup: Unable to load dynamic library 'memcache' in Unknown on line 0

### ISSUE THREAD

**Issue by eastygh** [nono303/PHP7-memcache-dll#9]
Cant load extension.
MS VCRedis2017 is installed
I tried this ->https://github.com/nono303/PHP7-memcache-dll/blob/master/vc15/x86/ts/php-7.2.x_memcache.dll
What i doing wrong?)

System => Windows NT EDESKTOP-01 10.0 build 17134 (Windows 10) i586
Build Date => Oct 10 2018 02:03:59
Compiler => MSVC15 (Visual C++ 2017)
Architecture => x86
Configure Command => cscript /nologo configure.js  "--enable-snapshot-build" "--enable-debug-pack" "--with-pdo-oci=c:\php-snap-build\deps_aux\oracle\x86\instantclient_12_1\sdk,shared" "--with-oci8-12c=c:\php-snap-build\deps_aux\oracle\x86\instantclient_12_1\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
Server API => Command Line Interface
Virtual Directory Support => enabled
Configuration File (php.ini) Path => C:\WINDOWS
Loaded Configuration File => C:\Develop\xampp\php\php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
PHP API => 20170718
PHP Extension => 20170718
Zend Extension => 320170718
Zend Extension Build => API320170718,TS,VC15
PHP Extension Build => API20170718,TS,VC15
Debug Build => no
Thread Safety => enabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

**Comment by nono303** [comment]
Hi @eastygh,
It probably deals with AVX architecture processor support 
Have a look at #8 and maybe try https://github.com/nono303/PHP7-memcache-dll/blob/master/vc15/x86/ts/avx/php-7.2.x_memcache.dll
What is your "i586" processor?

**Comment by eastygh** [comment]
Thx for answer. No, AVX not working too. Just freeze about 2-4 seconds and nothing. Nothing output into console.
PS C:\Develop\xampp> php -v
PS C:\Develop\xampp>

Without avx:
PS C:\Develop\xampp> php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcache' (tried: C:\Develop\xampp\php\ext\memcache (═х эрщфхэ єърчрээ√щ ьюфєы№.), C:\Develop\xampp\php\ext\php_memcache.dll (═х эрщфхэ єърчрээ√щ ьюфєы№.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'memcache' (tried: C:\Develop\xampp\php\ext\memcache (═х эрщфхэ єърчрээ√щ ьюфєы№.), C:\Develop\xampp\php\ext\php_memcache.dll (═х эрщфхэ єърчрээ√щ ьюфєы№.)) in Unknown on line 0
PHP 7.2.11 (cli) (built: Oct 10 2018 02:39:52) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
PS C:\Develop\xampp>

**Comment by eastygh** [comment]
This commit https://github.com/nono303/PHP7-memcache-dll/commit/a56b97b5ed6ce0e38d4287f0564c3085b275642a for x64 only, for x86 unnecessary fix?
mb same problem?
I have 7.2.11 version of php for x86

**Comment by nono303** [comment]
Hi @eastygh 
Effectively, I’ve forget some files in last commit for x86... Apologies!
So, I’ve rebuilt all ext. for all arc & co. with MSVC 15.8.8 and test them with https://windows.php.net/downloads/releases/php-7.2.11-Win32-VC15-x86.zip successfully on a standard seven computer

----

> Php.ini : 
> [Memcache]
> extension=E:/telecharger/php-7.2.11-Win32-VC15-x86/ext/php_memcache-x86-ts.dll

```
$ sha256sum.exe php_memcache-x86-ts-avx.dll
a6fb32885c3678d7b80c073db7c004c7f2b8a8b48c87436adfa80a9da54b3df4 *php_memcache-x86-ts-avx.dll
$ ./php -m | grep memcache
memcache
```

----

> Php.ini : 
> [Memcache]
> extension=E:/telecharger/php-7.2.11-Win32-VC15-x86/ext/php_memcache-x86-ts-avx.dll

```
$ sha256sum.exe php_memcache-x86-ts.dll
2d5099189f922de7cad7a8c606cbac8e4cea7aee470f25431b50aec5f985c11f *php_memcache-x86-ts.dll
$ ./php -m | grep memcache
memcache
```
So please, give me your feedback!

**Comment by eastygh** [comment]
It'is worked. Very big thx.
👍

**Comment by nasirmarediya** [comment]
[sdsd](url)
